name: OrisInfoInterface
version: '1.1'
main: com.lfmissonb.oris.OrisInfoInterface
api-version: '1.13'
load: STARTUP
authors: [ lfmissonb ]
description: A Minecraft plugin provides interfaces to get server infos.
website: darkglow.cn
